#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement

mkdir -p build

# libbluetooth-dev, libdbus-1-dev
# NOTE(Ryan): Annoyingly, include paths are not standard.
# So, $(pkg-config --list-all | grep dbus) && $(pkg-config --libs --cflags dbus-1)
gcc -I /usr/include/dbus-1.0 -I /usr/lib/x86_64-linux-gnu/dbus-1.0/include \
  code/bluetooth.c -o build/bluetooth -lbluetooth -ldbus-1

./build/bluetooth
