#!/bin/sh
# SPDX-License-Identifier: zlib-acknowledgement 

for test_binary in $(find build/ -maxdepth 1 -type f -iname "test-*"); do
  export TEST_FILE_NAME="${test_binary}" 
  script --quiet --command misc/run-qemu >/dev/null
  # TODO(Ryan): Process output here to determine if error occurred and terminate
  # grep '(qemu)' typescript
  # cat typescript | tr -d '\r'
  cat typescript
done

# NOTE(Ryan): QEMU variants:
#   1. Qemu user is for linux arm binaries (defaults cortex-a)
#    > qemu-arm -S -g 1234 build/tra
#   2. Supports baremetal
#    > qemu-system-arm -S -machine raspi2 -g 1234 build/tra
#   3. Old version of qemu, however supports more stm32 boards
#    > qemu-system-gnuarmeclipse -S -gdb tcp::1234 --nographic --no-reboot \
#     --board STM32F4-Discovery --mcu STM32F429ZI \
#     --semihosting-config enable=on,target=native --image "build/test-tem.elf" 
# To Debug:
#    > arm-none-eabi-gdb -q --nh -ex 'file build/test-tem.elf' -ex 'target remote localhost:1234'
